"""One package, one readiness report. Missing evidence is a failed check."""
import ast
import io
import json
import re
import subprocess
import unittest

from . import live, profiles, replay, runtime

FAULTS = ("silence", "disconnect", "invalid_frame", "coalesced", "repeated", "unsupported_command")


def protected_names(root):
    names = set()
    for path in (root / "tests/pins").glob("*/*.json"):
        pin = profiles.read_json(path)
        model = pin["model"].casefold()
        names.add(model)
        brand = path.parent.name
        if model.startswith(brand + " "):
            names.add(model[len(brand) + 1:])
        name = pin.get("session", {}).get("name")
        if name:
            names.add(name.casefold())
    for path in root.glob("*-bridge"):
        for node in ast.parse(path.read_text()).body:
            if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "MODELS" for t in node.targets):
                try:
                    rows = ast.literal_eval(node.value)
                except (ValueError, TypeError):
                    continue
                names.update(k.casefold() for k in rows if isinstance(k, str))
    return names


def no_legacy_claim(profile, root):
    names = {n.casefold() for n in profile["match"]["names"]}
    if profile["adapter"].get("builtin") == "nothing":
        names.update(n.removeprefix("nothing ") for n in list(names))
    collisions = names & protected_names(root)
    if collisions:
        raise ValueError("already supported owner model: " + ", ".join(sorted(collisions)))


def generate(root=profiles.ROOT, write=False):
    rows = profiles.registry(root)
    for path in profiles.packages(root):
        no_legacy_claim(profiles.load(path.parent), root)
    block = "// BEGIN DEVICE REGISTRY -- generated by tools/add-device sync\nvar DEVICE_PROFILES = " + json.dumps(rows, indent=2, ensure_ascii=True) + "\n// END DEVICE REGISTRY"
    path = root / "Model.js"
    source = path.read_text()
    pattern = r"// BEGIN DEVICE REGISTRY.*?// END DEVICE REGISTRY"
    if len(re.findall(pattern, source, re.S)) != 1:
        raise ValueError("Model.js needs exactly one generated registry block")
    outputs = {path: re.sub(pattern, lambda _m: block, source, flags=re.S)}
    text = "<!-- BEGIN DEVICE PACKAGES -->\n"
    if rows:
        text += "\nModels contributed through the device API:\n\n| Model | Confirmed controls | Owner |\n|:--|:--|:--|\n"
        for row in rows:
            profile = profiles.load(root / "devices" / row["id"])
            model = profile["model"].replace("|", "\\|").replace("\n", " ")
            modes = " · ".join(profile["capabilities"]["modes"])
            owner = profile["owner"]
            text += f"| [{model}](devices/{row['id']}/device.json) | {modes} | [@{owner}](https://github.com/{owner}) |\n"
        text += "\n"
        for row in rows:
            text += f"[![{row['id']}](devices/{row['id']}/screenshot.png)](devices/{row['id']}/screenshot.png)\n\n"
    text += "<!-- END DEVICE PACKAGES -->"
    path = root / "README.md"
    source = path.read_text()
    pattern = r"<!-- BEGIN DEVICE PACKAGES -->.*?<!-- END DEVICE PACKAGES -->"
    if len(re.findall(pattern, source, re.S)) != 1:
        raise ValueError("README needs exactly one generated device section")
    outputs[path] = re.sub(pattern, lambda _m: text, source, flags=re.S)
    changed = []
    for path, content in outputs.items():
        if path.read_text() != content:
            changed.append(str(path.relative_to(root)))
            if write:
                path.write_text(content)
    if changed and not write:
        raise ValueError("generated files are stale: " + ", ".join(changed) + "; run tools/add-device sync")
    return changed


def fault_tests(directory):
    path = directory / "test_adapter.py"
    module = runtime.load_module(path)
    suite = unittest.defaultTestLoader.loadTestsFromModule(module)

    def flatten(suite):
        for test in suite:
            if isinstance(test, unittest.TestSuite):
                yield from flatten(test)
            else:
                yield test

    ids = [test.id().rsplit(".", 1)[-1] for test in flatten(suite)]
    missing = ["test_" + name for name in FAULTS if "test_" + name not in ids]
    if missing:
        raise ValueError("missing model fault scenarios: " + ", ".join(missing))
    output = io.StringIO()
    result = unittest.TextTestRunner(stream=output, verbosity=1).run(suite)
    if not result.wasSuccessful() or result.skipped or result.expectedFailures:
        raise ValueError(output.getvalue().strip() + "; skipped or expected-failure scenarios are incomplete")
    return str(result.testsRun) + " model fault tests"


def readiness(directory, root=profiles.ROOT):
    result = {"device": directory.name, "checks": []}

    def check(label, fn):
        try:
            detail = fn()
            result["checks"].append({"check": label, "passed": True, "detail": detail or "OK"})
            return detail
        except (Exception, SystemExit) as error:
            result["checks"].append({"check": label, "passed": False, "detail": str(error)})
            return None

    profile = check("profile", lambda: profiles.load(directory))
    if profile is None:
        result["passed"] = False
        return result
    result["checks"][-1]["detail"] = "API v1"
    check("existing models", lambda: no_legacy_claim(profile, root))

    def identification():
        record = profiles.identity((directory / "identity.txt").read_text())
        if record["name"] not in profile["match"]["names"] or not set(profile["match"]["uuids"]).issubset(record["uuids"]):
            raise ValueError("profile name/UUIDs are absent from identity.txt")
        return "reported name and UUIDs match identity.txt"

    check("identification", identification)

    def adapter():
        if profile["adapter"].get("module"):
            path = profiles.inside(directory, "adapter.py")
            ast.parse(path.read_text())
            return "package-local adapter; contract exercised by replay and model tests"
        return profile["adapter"]["builtin"] + " with model-local parameters"

    check("adapter", adapter)
    checked = check("capture and replay", lambda: sorted(replay.verify(profile, directory)))
    if checked is not None:
        wanted = set(profiles.cases(profile)) - {"reconnect", "restoration"}
        if profile["capabilities"].get("battery", {}).get("source") != "bridge":
            wanted = {c for c in wanted if not c.startswith("battery:")}
        missing = sorted(wanted - set(checked))
        result["checks"].append({"check": "capability evidence", "passed": not missing,
                                 "detail": "missing cases: " + ", ".join(missing) if missing else "all declared controls have asserted replies"})
    check("fault scenarios", lambda: fault_tests(directory))

    def hardware():
        report = profiles.read_json(directory / "hardware-check.json")
        if report.get("apiVersion") != 1 or report.get("device") != profile["id"] or report.get("owner") != profile["owner"]:
            raise ValueError("hardware report must identify this device and owner")
        if report.get("implementation") != profiles.implementation_hash(profile, directory, root):
            raise ValueError("hardware report is stale for this executable/profile; rerun live check")
        if report.get("passed") is not True or not report.get("initial"):
            raise ValueError("owner adapter check failed or has no initial state")
        if not report.get("restoration") or not all(r.get("passed") is True for r in report["restoration"]):
            raise ValueError("initial settings were not confirmed restored")
        required = {case for case, *_ in live.controls(profile)}
        observed = set()
        for item in report.get("checks", []):
            if item.get("passed") is True:
                replay.validate_case(item["case"], item["reported"])
                observed.add(item["case"])
        if required - observed:
            raise ValueError("hardware report misses controls: " + ", ".join(sorted(required - observed)))
        return "owner adapter check passed; manual integration evidence checked separately"

    check("owner hardware", hardware)

    def manual():
        report = profiles.read_json(directory / "owner-checks.json")
        if report.get("owner") != profile["owner"] or report.get("implementation") != profiles.implementation_hash(profile, directory, root):
            raise ValueError("owner checks must name the owner and current implementation hash")
        required = {"shell-integration", "reconnect"}
        caps = profile["capabilities"]
        if caps.get("worn"):
            required.update(("worn:on", "worn:off"))
        if caps.get("battery", {}).get("source") != "bridge":
            required.update("battery:" + p for p in caps.get("battery", {}).get("parts", []))
        checks = report.get("checks", {})
        for key in sorted(required):
            record = checks.get(key, {})
            if record.get("status") != "passed" or not isinstance(record.get("evidence"), str) or not record["evidence"].strip():
                raise ValueError("missing owner observation: " + key)
        for key in ("peer-isolation", "charging", "acoustics"):
            record = checks.get(key, {})
            if record.get("status") not in ("passed", "untested", "not-applicable") or not record.get("evidence"):
                raise ValueError("state result or limit for " + key)
        limits = [key for key, item in checks.items() if item.get("status") != "passed"]
        return "owner attestation; limits: " + (", ".join(limits) or "none declared")

    check("owner integration and limits", manual)

    def screenshot():
        image = directory / "screenshot.png"
        if not image.read_bytes().startswith(b"\x89PNG\r\n\x1a\n"):
            raise ValueError("screenshot.png must be the owner's real panel screenshot")
        return "PNG present; visual/hardware authenticity remains an owner claim"

    check("gallery", screenshot)
    def protocol_notes():
        notes = (directory / "protocol.md").read_text().strip()
        if not notes or "Describe observed requests" in notes:
            raise ValueError("describe observed protocol and limits in protocol.md")
        return "protocol notes present"

    check("protocol notes", protocol_notes)
    result["passed"] = all(item["passed"] for item in result["checks"])
    return result


def immutable(root=profiles.ROOT, base=None):
    if not base:
        return "no base supplied; package ownership comparison not run"
    since = subprocess.check_output(["git", "merge-base", base, "HEAD"], cwd=root, text=True).strip()
    changed = subprocess.check_output(["git", "diff", "--diff-filter=MDR", "--name-only", since, "--", "devices"],
                                      cwd=root, text=True).splitlines()
    protected = [p for p in changed if len(p.split("/")) >= 3]
    if protected:
        raise ValueError("existing owner packages changed: " + ", ".join(protected))
    return "existing owner packages unchanged"


def markdown(reports):
    lines = ["| Device | Check | Result | Detail |", "|:--|:--|:--|:--|"]
    for report in reports:
        for item in report["checks"]:
            detail = str(item["detail"]).replace("|", "\\|").replace("\n", " ")
            lines.append("| %s | %s | %s | %s |" % (report["device"], item["check"], "OK" if item["passed"] else "MISSING / FAILED", detail))
    return "\n".join(lines)
